version: '3'
services:
    jenkins:
        # image: jenkins/jenkins:lts
        image: ffritz92/jenkins-docker:1.0
        container_name: jenkins
        volumes:
            - /data/jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 9090:8080
            - 5000:5000

networks:
    default:
        external:
            name: artifacts_docker-num-network
